ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/beats/packetbeat:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu