version: '3.8'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    networks:
      - elk
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - '5601:5601'
    networks:
      - elk
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/"]

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true    
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch      
  checkmk:
    build:
      context: checkmk/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: volume
        source: checkmk
        target: /omd/sites
    ports:
      - '8080:5000'
      - '6557:6557'
    networks:
      - elk
    depends_on:
      - elasticsearch

  netscaler:
    build:
      context: netscaler/
    volumes:
      - type: volume
        source: netscaler
        target: /cpx
      - type: bind
        source: ./etc/cpx.conf
        target: /etc/cpx.conf
        read_only: true
    environment:
      - EULA=yes
      - CPX_CONFIG='{"YIELD":"Yes"}'
    ports:
      - '9443:9443'
      - '22:22'
      - '443:443'
      - '80:80'
      - '9080:9080'
      - '88:88'
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      - elk
    tty: true
    depends_on:
      - elasticsearch

  sidecar:
    build: ./sidecar
    image: sidecar
    volumes:
      - type: bind
        source: ./sidecar/cpx_tmp.ps1
        target: /tmp/cpx_tmp.ps1
        read_only: true
    networks:
      - elk
    depends_on:
      - netscaler
      - consul-server-bootstrap


  consul-server-bootstrap:
    image:  consul:latest
    command: "agent -server -ui -client 0.0.0.0 -bootstrap-expect=3"
    networks:
      elk:
        aliases:
          - consul
    ports:
      - "8500:8500"
    depends_on:
      - netscaler
      - elasticsearch

  consul-server-1:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      elk:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap

  portainer:
    image:  portainer/portainer:latest
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock  
      - type: volume
        source: portainer
        target: /data  
    ports:
      - '9000:9000'
    networks:
      - elk

  heartbeat:
    build:
      context: heartbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - output.elasticsearch.hosts= elasticsearch:9200
      - setup.kibana.host= kibana:5601
    user: root
    volumes:
      - type: bind
        source: ./heartbeat/heartbeat.yml
        target: /usr/share/heartbeat/heartbeat.yml 
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    depends_on:
      - elasticsearch
    command: heartbeat -e -strict.perms=false
    networks:
      - elk

  metricbeat:
    build:
      context: metricbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - output.elasticsearch.hosts= elasticsearch:9200
      - setup.kibana.host= kibana:5601
    user: root
    volumes:
      - type: bind
        source: ./metricbeat/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml 
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
    depends_on:
      - elasticsearch
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    networks:
      - elk

  packetbeat:
    build:
      context: packetbeat/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - output.elasticsearch.hosts= localhost:9200
      - setup.kibana.host= localhost:5601
    user: root
    volumes:
      - type: bind
        source: ./packetbeat/packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml 
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    depends_on:
      - elasticsearch
    command: packetbeat -e -strict.perms=false
    cap_add: ['NET_RAW', 'NET_ADMIN']
    network_mode: host



  consul-server-2:
    image:  consul:latest
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"
    networks:
      elk:
        aliases:
          - consul
    depends_on:
      - consul-server-bootstrap

  registrator:
    image: gliderlabs/registrator:latest
    command: "-cleanup -resync 5 consul://consul-server-bootstrap:8500"
    networks:
      - elk
    container_name: registrator
    depends_on:
      - consul-server-bootstrap
      - consul-server-1
      - consul-server-2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

networks:
  elk:
    driver: bridge
volumes:
  elasticsearch: null
  checkmk: null
  netscaler: null
  portainer: null
